USE [master]
GO

/****** Object:  Database [dba_utils]    Script Date: 3/13/2015 9:14:34 PM ******/
CREATE DATABASE [dba_utils]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dba_utils', FILENAME = N'E:\SQL_Data\dba_utils.mdf' , SIZE = 512 MB , MAXSIZE = 2048 MB, FILEGROWTH = 512 MB ), 
 FILEGROUP [partition_indexes] 
( NAME = N'partition_indexes_01', FILENAME = N'P:\SQL_Data\partition_indexes_01.ndf' , SIZE = 256 MB , MAXSIZE = 4096 MB , FILEGROWTH = 256 MB ), 
 FILEGROUP [partition_tables] 
( NAME = N'partition_tables_01', FILENAME = N'K:\SQL_Data\partition_tables_01.ndf' , SIZE = 512 MB , MAXSIZE = 4096 MB , FILEGROWTH = 512 MB )
LOG ON 
( NAME = N'dba_utils_log', FILENAME = N'L:\SQL_Logs\dba_utils_log.ldf' , SIZE = 256 MB , MAXSIZE = 2048 MB , FILEGROWTH = 256 MB );
GO

--ALTER DATABASE [dba_utils] SET COMPATIBILITY_LEVEL = 120
--GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
EXEC [dba_utils].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO

ALTER DATABASE [dba_utils] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dba_utils] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dba_utils] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dba_utils] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dba_utils] SET ARITHABORT OFF 
GO

ALTER DATABASE [dba_utils] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dba_utils] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dba_utils] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dba_utils] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dba_utils] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dba_utils] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dba_utils] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dba_utils] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dba_utils] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dba_utils] SET  ENABLE_BROKER 
GO

ALTER DATABASE [dba_utils] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [dba_utils] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dba_utils] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dba_utils] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dba_utils] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dba_utils] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dba_utils] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dba_utils] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dba_utils] SET  MULTI_USER 
GO

ALTER DATABASE [dba_utils] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dba_utils] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dba_utils] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dba_utils] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dba_utils] SET  READ_WRITE 
GO


